### ISSUE TITLE
FPGA clock accuracy vs tracking accuracy

### ISSUE THREAD

**Issue by NicksonYap** [bitcraze/lighthouse-fpga#1]
Hi, 

I was studying how the lighthouse deck works and came across this component in the schematic and the repo mentioning: 

> The pulses are measured in a 48MHz clock

![image](https://user-images.githubusercontent.com/5380731/61181807-9a281c00-a65d-11e9-8b0e-71edf6d09843.png)

Am I right that the DSC600X is actually 48mhz, and is the more accurate +-25ppm version?
standard version is +-50ppm

Would there be any difference if TCXO were used?

So if the clock were to deviate, the tracking would also deviate?

Thanks

**Comment by ataffanel** [comment]
Yes the lighthouse deck uses a DSC600x MEMs oscillator. It is running at 12MHz, +/-25ppm. A [PLL](https://github.com/bitcraze/lighthouse-fpga/blob/1e7dfea/pll.v) in the fpga generates a 24MHz clock from it and DDR inputs are used to sample the signal at 48MHz.

I do not think using a TCXO would make any noticeable difference in the actual tracking accuracy but this is not something we have investigated thoroughly.
