### ISSUE TITLE
Error while running search-seed

### ISSUE THREAD

**Issue by rashmiam12** [bitcraze/lighthouse-fpga#11]
when i run the search-seed script I get the following error

Warning: Use of default value for --package is deprecated. Please add '--package sg48' to arguments.
ERROR: Failed to open JSON file 'lighthouse.json'.
1 warning, 1 error

Can someone please help me with this ?

**Comment by ataffanel** [comment]
It looks like the package parameter needs to be added when calling nextpnr. I just tested using the latest version of nextpnr and I did not have the problem though. I anyway pushed a fix that adds the parameter, tell me if it works and we can close this issue.

**Comment by rashmiam12** [comment]
Thanks for the reply! yes it is working now.

**Comment by ataffanel** [comment]
Great! Closing this issue then :-)
