### ISSUE TITLE
LH Deck sometimes require power cycle to reactivate some sensors

### ISSUE THREAD

**Issue by NicksonYap** [bitcraze/lighthouse-fpga#2]
Hi,

I've been actively doing tests & development with the 2 LH Deck I have

Initially I noticed the CF will require a restart when some the Lighthouse quality LED effect is not fully green (red when no sensors produce a position, green when all 4 sensors produce a position)

I would notice sometimes a CF will be fully green. and another CF will be less green or even orange (1 or more sensors not working)
Re-positioning it did not help but turns green only after a restart

Now that I've been developing on Eclipse, I added sequence to reset the FGPA on boot of the CF MCU because the lighthouse deck would not work after programming the CF using debugger

Even with a software reset of the FPGA, the behaviour still exists.
Once in a while I notice a sensor is not working and I have to power cycle.
CF Reset and FPGA Reset did not work.

I suspect other ICs/chips on the LH is affected, probably require some re-initialization of other ICs from the FPGA end

Not a big issue, but it might be possible for sensors to fail during flight
And work only after a power cycle

I'm planning to have CFs flying non stop (ICRA 2019 demo) so this can be a pain point

Thanks!

**Comment by ataffanel** [comment]
There has been a sensor initialization delay fixed during the summer, the resulting bitstream was used during production but I had not taken the time releasing it. 

I have now released the V2 bitstream with this fix: https://github.com/bitcraze/lighthouse-fpga/releases/tag/V2. I updated the bitstream in the Crazyflie firmware as well.

Please tell me if you see an improvement.
